"""add chatbot model

Revision ID: a6c712365498
Revises: eb0dc179c935
Create Date: 2025-10-22 22:19:19.298056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6c712365498"
down_revision: Union[str, Sequence[str], None] = "eb0dc179c935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chatbots", sa.Column("name", sa.String(), nullable=False))
    op.add_column("chatbots", sa.Column("description", sa.String(), nullable=False))
    op.add_column(
        "chatbots",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
    )
    op.add_column(
        "chatbots",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_chatbots_description"), "chatbots", ["description"], unique=False
    )
    op.create_index(op.f("ix_chatbots_name"), "chatbots", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chatbots_name"), table_name="chatbots")
    op.drop_index(op.f("ix_chatbots_description"), table_name="chatbots")
    op.drop_column("chatbots", "updated_at")
    op.drop_column("chatbots", "created_at")
    op.drop_column("chatbots", "description")
    op.drop_column("chatbots", "name")
    # ### end Alembic commands ###
