"""add chatbot is_activate field

Revision ID: eae3995f6a19
Revises: a6c712365498
Create Date: 2025-10-22 22:38:24.567069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eae3995f6a19"
down_revision: Union[str, Sequence[str], None] = "a6c712365498"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chatbots", sa.Column("system_prompt", sa.Text(), nullable=True))
    op.add_column("chatbots", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.alter_column(
        "chatbots",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.drop_index(op.f("ix_chatbots_description"), table_name="chatbots")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_chatbots_description"), "chatbots", ["description"], unique=False
    )
    op.alter_column(
        "chatbots",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("chatbots", "is_active")
    op.drop_column("chatbots", "system_prompt")
    # ### end Alembic commands ###
